### ISSUE TITLE
Should I Use the TTF or OTF Version for a Printed Document?

### ISSUE THREAD

**Issue by amarz45** [georgd/EB-Garamond#181]
I read this on the [Wikipedia article](https://en.wikipedia.org/wiki/EB_Garamond#Technical_details) for this typeface:

> The source of the fonts is drawn with cubic Bézier curves, thus the OTF-version (CFF-style) version of the compiled fonts should be preferred over the TTF-version, as TTF requires quadratic Bézier curves which have to be generated by lossy conversion during the compilation from the source files.

But I read [this](http://www.georgduffner.at/ebgaramond/features.html) on the EB Garamond website:

> OpenType fonts come in two flavours that differ in the way the outlines are described, the one containing cubic bezier splines (cff fonts, usually as otf-files), the others containing quadratic bezier splines (Truetype fonts, usually as ttf-files). Also, ttf-files contain much more sophisticated hinting which is necessary to make fonts look acceptable on most Windows systems.

Is it true that the TTF version has been lossily converted from the OTF version? Also, I noticed how you said “which is necessary to make fonts look acceptable on most Windows systems”. I am using a Linux-based operating system. Is the better hinting still preferable in this case? So which file format should I use for a printed document?

**Comment by georgd** [comment]
It's correct that the conversion from the sources which are drawn with cubic Bézier curves to TTFs  is lossy by nature because approximation and rounding plays a role. At normal text sizes it probably doesn't matter much. 

The information about Windows is now more than ten years old and might not be relevant any longer but I'm not sure. I usually only install the OTF version. The hinting only plays a role on screen so for printing you can choose either version, but I'd go with OTF.

**Comment by amarz45** [comment]
> The hinting only plays a role on screen so for printing you can choose either version, but I'd go with OTF.

Thanks, I’ll go with OTF then.
