### ISSUE TITLE
Readability of small italic h

### ISSUE THREAD

**Issue by rikhuijzer** [georgd/EB-Garamond#206]
Thank you Georg and Octavio for making this font freely available. I think it's a great font and I am a happy user.

One small issue that I have is with the readability of the small italic letter _h_. I'm currently converting a book, for example, where they use the word _Ehrenstaat_ (meaning _honorary state_ in German, but it doesn't matter for this issue).

In the original book from the 1900s, the word looks as follows:

![image](https://github.com/user-attachments/assets/d9e4ab2f-834d-4ee9-9f13-e9d0775e72a3)

But in the EM Garamond version, it looks like this:

![image](https://github.com/user-attachments/assets/3380efaa-8c53-42a3-babf-6b0655bb856e)

Would it be possible for EM Garamond to angle the right descender of the letter _h_ to the right instead of the left? When zoomed out, it is currently somewhat difficult to distinguish the italic _h_ from a _b_.

**Comment by davidpiano** [comment]
The shape of the italic h is an intentional feature of this style, not a defect. I think you are probably right to say that more modern designers (such as the one in the book from the 1900s) have developed a functionally better italic h, but **this** font is intended to be a faithful reproduction of the design of its source – an idealized snapshot of history – so giving this font a more modern style probably wouldn't make sense.

**Comment by Omikhleia** [comment]
> The shape of the italic h is an intentional feature of this style,

And I really like this shape, personally, better that the 1900 one shown above.

Well, that's where OpenType stylistic sets could be used -- but @georgd et al. probably have a lot of other issues and topics to deal with first, before considering stylistic sets for variant shapes.

**Comment by ArchangeGabriel** [comment]
I can confirm that my students always take them for b, but I take that as an example for “you should read carefully”.

**Comment by rikhuijzer** [comment]
Okay thank you for the clarification. Sounds reasonable to me and I'll close this
