### ISSUE TITLE
Ongoing development?

### ISSUE THREAD

**Issue by dpk** [georgd/EB-Garamond#75]
Sorry, I know this is an inappropriate use of an issue, but … is this font still being developed? There are no commits in over a year now.

**Comment by luc--** [comment]
It seems so :
https://github.com/georgd/EB-Garamond/network

**Comment by georgd** [comment]
Luc and David, very little development happened in the last 18 months for personal reasons. in the past two years, I graduated, finished a post graduate program, got a new job and a daughter. I plan to resume working on the project soon but at a not too fast pace for some time to come. However, still this year you’ll see a bold companion to EB Garamond 12 drawn by Octavio Pardo from Spain who has been commissioned by Google for this task.

**Comment by dpk** [comment]
Understood. Congratulations on the new job and daughter, and good luck.

**Comment by markvanatten** [comment]
Indeed -- Congratulations and good luck!

**Comment by JorgeRaimundo** [comment]
Excellent news on your personal life!
I'm glad to see that you have been successful at studies/work and family.
Your family is the most important thing (I'm a father of three boys :D )
I found this font by accident and immediately fell in love with it. It's beautiful, perfect. Such care for detail and features.
When I saw that the last commit was done more than a year ago I started to be worried, since there is no bold font and the initials are not finished, but now I found this reply of yours and I'm relieved.
If in deed we manage to have the bold part this year it would be great and I would stop looking for any other fonts, because the one would fill the gaps I still have.
Congratulations on the font, it's really good, please don't let it unfinished.
After the bold, if the initials and the letrines start to appear again it would be great. Try to add two or three initials every year :stuck_out_tongue: Seriously, don't let your family time pass by you because of this.
It would be great to give this project more visibility and attract more people willing to make it advance to completion.
Thank you very much for all your work and dedication.

**Comment by ArchangeGabriel** [comment]
What news on this bold font? I found some work here: https://github.com/octaviopardo/EBGaramond12.

The bold font is the only thing I lack in my TeX install to start using EB Garamond in production.

**Comment by georgd** [comment]
Hi Bruno,

the work you detected is the bold font I talked about. Its set is complete, now it’s being reviewed.

**Comment by ArchangeGabriel** [comment]
Nice to hear! Good luck reviewing all those glyphs, I suppose this takes a lot of time to do.

**Comment by ChristTrekker** [comment]
Georg, great to hear about your personal successes and coming development on EBG. (Hopefully having Google behind development means it will serve a newer version soon. Much has changed since the old version it has now.) I'm afraid I haven't been able to devote any time to my branch recently.

**Comment by aminb** [comment]
@georgd Any news about the review of the bold font?

**Comment by martindonat** [comment]
@georgd Anything new? There seem to be no changes in Octavio Pardo's Repo for some months now...

**Comment by ArchangeGabriel** [comment]
The latest commits still says the font needs a lot of reviewing and “super & intense polishment”. So it’s not done yet. But I agree some news or status update would be welcome. ;)

**Comment by martindonat** [comment]
FYI: Octavio released otf files for a medium, semi-bold, bold and extra-bold font. I think they are not reviewed yet, but they already look very good. You can find them here:

https://github.com/octaviopardo/EBGaramond12/tree/master/Fonts

**Comment by ArchangeGabriel** [comment]
FYI: Octavio released a new version, 0.8, fixing a lot of issues and adding some characters.

**Comment by jenstroeger** [comment]
> Octavio released a new version, 0.8, fixing a lot of issues and adding some characters.

How does [Octavio’s implementation](https://github.com/octaviopardo/EBGaramond12) relate to the work in this repo?

**Comment by ArchangeGabriel** [comment]
It’s almost a superset, Octavio initially added bold variants, but then started adding missing characters and fixing spacing/kerning of existing ones. Only some Unicode features that are available here are missing in his release, as well as Initials that can still be grabbed from here.

**Comment by georgd** [comment]
@jenstroeger Octavio was commissioned to create bold fonts for EBG. While working on it he also corrected issues he found in the drawings and especially spacing/kerning.

His part is currently at a state that I restarted work on the feature files to restore the more or less sophisticated open type features that IMO are a strong part of these fonts, and to extend them also to the newly created bold fonts.

The next step from my side will be to fix mark and mark to mark anchor placement which got more or less destroyed.

I’m not sure yet how to proceed with the git repositories so I can’t give an answer on this kind of relationship.

**Comment by davelab6** [comment]
> The next step from my side will be to fix mark and mark to mark anchor placement which got more or less destroyed.

I see some work on the feature file of the italic in https://github.com/georgd/EB-Garamond/commit/97f3dd1bd8b645314d1c3ce13d4d373549787a73 

However, I think @octaviopardo already started work on fixing the anchor placement. Octavio, please comment :)

cc @m4rc1e

**Comment by ArchangeGabriel** [comment]
I’m not sure that @octaviopardo receives notifications for messages in this repository.

**Comment by octaviopardo** [comment]
I do not! Sorry, I ll review the repository in the following days :)El 27 oct. 2017 6:47 p. m., Bruno Pagani <notifications@github.com> escribió:I’m not sure that @octaviopardo receives notifications for messages in this repository.

**Comment by davelab6** [comment]
@octaviopardo what is the status of the mark/anchor placement

**Comment by octaviopardo** [comment]
already touched a little bit in the last update, In the following updates will be more improved



El 3 de noviembre de 2017 a las 5:02:58, Dave Crossland (notifications@github.com) escribió:

@octaviopardo what is the status of the mark/anchor placement

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

Octavio Pardo Virto
Graphic Designer /Type Designer
C/ Berriozar 21, 
Oficina 36, 2º piso
31013 Pamplona SPAIN
+34 657 106 116
www.octaviopardo.com

**Comment by KrasnayaPloshchad** [comment]
Georg, I suggest creating a GitHub organization and then moving this repo into there, with these steps everyone who has experiences on typography could having rights for maintaince and new release.

**Comment by ArchangeGabriel** [comment]
@KrasnayaPloshchad There is no need for an organization to give other people such rights.

**Comment by waldyrious** [comment]
@ArchangeGabriel for non-org repositories, additional people can only be added as collaborators, i.e. they'd have push rights, but no way to add other collaborators, or perform other administrative tasks. So the goal of preventing a single point of failure would not be achieved, since the repo owner would remain the only person able to do those things, and therefore the entire project woudl remain dependent on them.

AFAIK an organization is the only way (on GitHub) to allow projects to "self-heal" as its maintainers' availability fluctuates over time.

**Comment by ArchangeGabriel** [comment]
OK, wasn’t aware of the differences. However, forks are a thing, and in the current case the released code is not here anymore, but at https://github.com/octaviopardo/EBGaramond12/.

**Comment by georgd** [comment]
Dear all,

I’ll reorganize all this, once outstanding changes have been made by
Octavio.



2018-04-12 12:25 GMT+02:00 Bruno Pagani <notifications@github.com>:

**Comment by mgavioli** [comment]
@octaviopardo 's work on the EB Garamond fork is a welcome new and a terrific endeavour to be highly praised.

However, it seems to me it is geared toward a somewhat different direction than this repo, possibly because of the Google commission: just to list a few details, it has upper case numerals by default, while all fonts here have lower case numerals by default (the only numerals making sense in a Garamond context); the Regular has been 'cleaned' up ('A' cross bar, 'E' serifs, etc.); the Italic lacks some of the distinctive ligatures of the originals, and so on.

If I can boldly summarise, it seems to me the goal of the fork is a Garamond-looking, general purpose, typeface; while -- if I am not mistaken -- the distinctive purpose of this project was the restitution of a historic typeface, as faithfully as possible given the difference of medium.

I hope the great and good work by Mr. Pardo could help revitalising this project, without changing its nature.

Thanks to everybody involved!

**Comment by davelab6** [comment]
The version on Google Fonts was already updated with Octavio's version.

**Comment by ArchangeGabriel** [comment]
@mgavioli This is right, Google has rules regarding what they want for their Google Fonts, and you can read about numerals here: https://github.com/octaviopardo/EBGaramond12/issues/13.

The conclusion is that we would have either two version of the font, which is not good for usability, or that we need a good UX for selecting everywhere that applies.

**Comment by mgavioli** [comment]
@ArchangeGabriel :

> The conclusion is that we would have either two version of the font, which is not good for usability

I beg to differ: we already have two versions of the font; even more, we have two different projects, sharing a number of glyphs, but with different goals and different perspectives.

Both are legitimate, of course, and either has its merits and its strong points. Trying to 'merge' them or to subsume both under a single umbrella would, IMHO, weaken those strong points and leave us with an unfocused 'super-project' lacking the merits of both parents.

Personally, I am particularly interested in the original project: there are not so many reliable restitutions of historic typefaces out there, almost none of them is open source and almost none refers to an original of such a historic relevance.

Then, I hope this project will not loose its original goal and focus.

I understand this does not appeal to everybody and does not fit all purposes; and this is why a more 'main stream' project like Mr. Pardo's, maybe drawing from the same source, but in a more generally useful way, is important. But, IMHO, it is a different project and should remain separate, with its own goal(s) and focus.

Thanks for reading!

**Comment by ArchangeGabriel** [comment]
@mgavioli I’m not the one to be convinced, I was just merely reporting to you the conclusion of the linked thread. You can read @georgd statement about this [here](https://github.com/octaviopardo/EBGaramond12/issues/13#issuecomment-353438828).
